## NiFi 설정
nifi:
  image: apache/nifi:latest
  container_name: nifi
  ports:
    - "8080:8080"
  environment:
    - TZ=Asia/Seoul
  links:
    # - mariadb:mariadb.com
    - mysql:mysql.com
  volumes:
    - D:\docker-data\container\nifi\volumes:/home/nifi
 
## MySQL
mysql:
  image: mysql:latest
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=1234
    - TZ=Asia/Seoul
